### ISSUE TITLE
스플래시 GROOV 로고가 보이지 않음

### ISSUE THREAD

**Issue by Mildwhale** [pilgwon/GROOV#34]
GROOV 로고가 보이지 않아서, 앱이 느리게 실행되는 것 같이 보여집니다.

**Comment by pilgwon** [comment]
실제 기기에서 인가요? 아니면 시뮬레이터에서 인가요?
저도 시뮬레이터로 돌릴 때는 GROOV 로고가 뜨지 않아서 고쳐야겠다고 생각했는데 실제 기기에서도 그러면 문제일 것 같네요..

**Comment by Mildwhale** [comment]
지금 배포된 버전에도 로고가 포함된것 아닌가요?
제 폰에서 최신버전으로 로고가 보이지 않고, 시뮬레이터에서도 로고가 보이지 않습니다. 😭

**Comment by Mildwhale** [comment]
LaunchScreen.storyboard 들어가보니, 이미지가 없다고 나오네요! 😭 
마스터 브랜치 기준입니다.

<img width="353" alt="스크린샷 2020-03-01 오전 11 26 57" src="https://user-images.githubusercontent.com/3113810/75618312-9f67b600-5baf-11ea-88e5-80933c144580.png">

**Comment by pilgwon** [comment]
#38 PR에서 해결해서 머지했는데 확인부탁드립니다!

**Comment by Mildwhale** [comment]
와우 수고하셨습니다 !
이제 잘 나오네요 💯💯💯💯💯
