### ISSUE TITLE
BaseViewController에서 Deprecated된 api 사용

### ISSUE THREAD

**Issue by Mildwhale** [pilgwon/GROOV#40]
```swift
func behavior() {
    automaticallyAdjustsScrollViewInsets = false
    // 'automaticallyAdjustsScrollViewInsets' was deprecated in iOS 11.0: Use UIScrollView's contentInsetAdjustmentBehavior instead
}
```

**Comment by pilgwon** [comment]
저 속성은 비디오 리스트 화면(플레이리스트 상세 화면)이 네비게이션 없이 상태바까지 영상을 꽉 채우려고 했을 때 넣어둔 속성인 것 같습니다. 그냥 지워버려도 문제없겠네요!

**Comment by Mildwhale** [comment]
> 저 속성은 비디오 리스트 화면(플레이리스트 상세 화면)이 네비게이션 없이 상태바까지 영상을 꽉 채우려고 했을 때 넣어둔 속성인 것 같습니다. 그냥 지워버려도 문제없겠네요!

나중에 BaseScrollViewController를 만들게 되면, 그때 ScrollView의 속성으로 설정하면 될 것 같습니다.
제가 비디오 리스트 작업하면서 같이 삭제하겠습니다. 🙂

**Comment by pilgwon** [comment]
#31 에서 해결됐으므로 닫겠습니다
