### ISSUE TITLE
VideoList에서 Video 추가/삭제 시 추가된 비디오가 선택 되지 않는 이슈

### ISSUE THREAD

**Issue by Mildwhale** [pilgwon/GROOV#41]
### 이슈
1. 비디오를 모두 삭제 후 Blank 뷰가 나왔을 때 바로 비디오를 추가하면, 추가 된 비디오로 선택이 되지 않고 이전에 선택했던 비디오가 플레이어에 보여집니다.

2. ~구현된 로직을 보았을 때, 비디오를 새로 추가하면 추가 한 비디오로 선택이 되어야 하는 것 같은데, 기능이 동작하지 않습니다.~

3. 1번 이슈가 재현된 상태에서, 추가된 다른 비디오를 터치하면 재생중이던 비디오가 다시 재생됩니다. (정확히는 같은 위치의 셀을 터치했을 때)

### 의견
비디오 추가/삭제 시 조건을 정의하고, 어떻게 동작하면 좋을지 논의가 필요할 것 같습니다.

**Comment by pilgwon** [comment]
지금 재생중인 비디오를 제거하면 제거된 결과물인 비디오 목록의 0번째에 있는 비디오를 선택해줘야하는데 그렇지 못하고 있는 것 같네요.
비디오가 하나도 없을 때는 새로 비디오를 추가하면 그 비디오를 선택해줘야 할 것 같고,
비디오가 1개 이상 남아있을 때 새로 비디오를 추가하는 것에 대해선 따로 처리하지 않아도 될 것 같습니다
비디오가 제거될 때는 남은 비디오의 0번째에 있는 비디오를 선택해주면 될 것 같습니다
이 이슈는 GROOV 처음부터 있었던 것 같은 이슈라 천천히 처리하면 될 것 같습니다
#42 이슈도 비슷한 이유로 선택된 비디오에 대한 정보를 제대로 못 가져와서 progressView의 width 조절을 위해 duration 을 이용한 계산을 하다가 문제가 생기는 것 같습니다.
지금 이슈를 해결하면 #42 는 자동으로 해결되지 않을까요?

**Comment by Mildwhale** [comment]
### 비디오 추가
#### 비디오 목록이 비어있을 때
1. 비디오 목록에 추가한다.
2. 추가된 비디오를 선택한다.

#### 비디오가 있을 때
* 비디오 목록의 제일 뒤에 이어붙인다.

### 비디오 삭제
#### 비디오 목록이 비었을 때
1. 캐시되어있는 모든 정보를 초기화 한다.
2. Blank 뷰를 보여준다.

#### 비디오가 있을 때
* 첫 번째 비디오를 선택한다.

**Comment by Mildwhale** [comment]
#42 이슈는 빈 목록에서 처음으로 재생할 때도 발생하는 것 같은데, 일단 해결 될 가능성은 있으리라 봅니다.

우선 시나리오를 정리해보고 이대로 수정 해보겠습니다. 
감사합니다. 😄

**Comment by pilgwon** [comment]
정리 정말 감사드립니다!!
