### ISSUE TITLE
자동완성이 불가능한 문자열에 대한 처리 추가

### ISSUE THREAD

**Issue by pilgwon** [pilgwon/GROOV#5]
동영상 검색 화면에서 `,` `!` 과 같은 특수문자를 입력하면 자동완성 목록이 나오지 않으면서 Activity Indicator가 계속해서 돌아가는 현상이 있습니다.

**Comment by Mildwhale** [comment]
검색 결과가 없을때의 처리를 좀 더 신경쓰는게 좋을 것 같습니다.

아래 커밋에서 작업 후 테스트중입니다. 🙂
https://github.com/Mildwhale/GROOV/commit/404db7e34008858b445264462872e56a0b679546
